# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39b8406842cb0a30ac35e589d3a530b8279503f959a50e9282b139707e891c0fc0b65c21aa450a207ea2cd3fee12a6a5c41142cf0edd31cf28a41bd9f1cb95ec

test:
  secret_key_base: 872718aa6d5bff0d3ff5db50dfb3f8ddf0fe1d1f12579754d27c6ce8470fc478b7c7dbe9ee5479329e7792105c9943c23064d1b70c82a42b2bc420c210e61ba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
